version: "3.8"
services:
  hivemq:
    image: hivemq/hivemq-ce
    ports:
      - "1883:1883"
    volumes:
      - ./hivemq/data:/opt/hivemq/data
      - ./hivemq/log:/opt/hivemq/log
      - ./hivemq/extensions:/opt/hivemq/extensions
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
      
