version: "3.8"
services:
  mosquitto:
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
      
