
@url = http://localhost:5000/accounts
@auth = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6InVzZXIiLCJuYmYiOjE2MDY0MjE3NzEsImV4cCI6MTYwNjQyNTM3MSwiaWF0IjoxNjA2NDIxNzcxfQ.CVEBV9KHKEox6rJOjxgOSamA3Nn6EctgO30osLKcAL0
### Get accounts
GET {{url}}
Authorization: {{auth}}

### Get account
GET {{url}}/6aa9dc50-ee96-4603-b031-ea3bd0487fe2

### Create account
POST {{url}}
Content-Type: application/json

{
    "Id": "{{$guid}}",
    "UserName": "user",
    "Password": "secret"
}

### login
POST {{url}}/login
Content-Type: application/json

{
    "UserName": "user",
    "Password": "secret"
}