
@url = http://localhost:5000/devices
@auth = BearereyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6InVzZXIiLCJuYmYiOjE2MDc4ODkyMTUsImV4cCI6MTYwNzg5MjgxNSwiaWF0IjoxNjA3ODg5MjE1fQ.BcohaqLAKWAemgH6RjZSSm60QvKYVlxfUL6wIbCzgVc
### Get Devices
GET {{url}}
Authorization: {{auth}}

### Get Devices
GET {{url}}/device1
Authorization: {{auth}}

### Create device
POST {{url}}
Content-Type: application/json
Authorization: {{auth}}

{
    "Id": "device2",
    "Enabled": true,
    "Password": "secret2"
}

### Update device
PUT {{url}}/device2
Content-Type: application/json
Authorization: {{auth}}

{
    "Enabled": true,
    "IsOperational": true,
    "SilentMode": true,
    "SerialNumber": 1234
}

### Update device password
PUT {{url}}/device2/update-password
Content-Type: application/json
Authorization: {{auth}}

{
    "Password": "secret"
}