
@url = http://localhost:5001/accounts
@auth = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6InVzZXIiLCJuYmYiOjE2MDY4MDU1NjUsImV4cCI6MTYwNjgwOTE2NCwiaWF0IjoxNjA2ODA1NTY1fQ.CkhcEJFO4jrO9YTbpZ7GV7ARUNfb2FyXmw0OQ81OHaw

### Create account
POST {{url}}
Content-Type: application/json

{
    "Id": "{{$guid}}",
    "UserName": "user",
    "Password": "secret"
}

### login
POST {{url}}/login
Content-Type: application/json

{
    "UserName": "user",
    "Password": "secret"
}